import localFont from "next/font/local";
import {getKindeServerSession, LoginLink, LogoutLink, RegisterLink} from "@kinde-oss/kinde-auth-nextjs/server";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const {isAuthenticated} = getKindeServerSession();
  const isAuthed = await isAuthenticated();
  
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-br from-purple-300 via-blue-200 to-gray-200 dark:from-purple-900  dark:to-blue-900 min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="fixed top-0 left-0 right-0 p-4 bg-white bg-opacity-50 backdrop-blur-md shadow-lg dark:bg-gray-800 dark:bg-opacity-50">
          <div className="container mx-auto flex items-center justify-between">
            <a href="/">
              <h1 className="pl-5 text-xl sm:text-3xl font-bold text-gray-800 dark:text-white">X-Ray Burst Analyzer</h1>
            </a>
            {isAuthed?
              <LogoutLink className="rounded-full border border-solid border-black/[.08] dark:border-white/[.145] transition-colors flex items-center justify-center hover:bg-[#f2f2f2] dark:hover:bg-[#1a1a1a] hover:border-transparent text-sm sm:text-base h-10 px-4">Logout</LogoutLink>
            :
            <div className="flex space-x-4">
            <LoginLink className="rounded-full border border-solid border-transparent transition-colors flex items-center justify-center bg-foreground text-background gap-2 hover:bg-[#383838] dark:hover:bg-[#ccc] text-sm sm:text-base h-10 px-4">
              Login
            </LoginLink>
            <RegisterLink className="rounded-full border border-solid border-black/[.08] dark:border-white/[.145] transition-colors flex items-center justify-center hover:bg-[#f2f2f2] dark:hover:bg-[#1a1a1a] hover:border-transparent text-sm sm:text-base h-10 px-4">
              Sign&nbsp;Up
            </RegisterLink>
          </div>
            }
            
          </div>
        </header>
        <main>
          {children}
        </main>

      </body>
    </html>
    
  );
}
